source: .
destination: ./_site
include: ['.htaccess']
exclue: []
keep_files: ['.git']

host: 0.0.0.0
port: 4000
baseurl: /
url: http://localhost:4000
lsi: false

name: peethwd.net
permalink: /blog/:year/:month/:day/:title
markdown: redcarpet
pygments: true


navigation:
- text: Home
  url: /
- text: Portfolio
  url: /portfolio/
- text: Blog
  url: /blog/
- text: Twitter
  url: "http://twitter.com/peethwd"
