source: .
destination: ./_site
include: ['.htaccess']
exclude: ['VagrantFile', 'bower.json', 'readme.md', ]
keep_files: ['.git']
timezone: Europe/London

host: 0.0.0.0
port: 4000
baseurl: 
url: http://localhost:4000
lsi: false

name: peethwd.net
permalink: /notes/:title
markdown: redcarpet
pygments: true
